### PR TITLE
Fix all clippy and compiler warnings and add clippy to CI

### LINKED ISSUE #114: Resolve clippy issues
After #112, builds now run clippy, but it outputs warnings. See https://travis-ci.org/github/ebfull/pcap/jobs/720888528.

They should be fixed so that CI can be setup to fail on clippy warnings with `cargo clippy -- -D warnings`.

### PR DESCRIPTION
**Pull request by Wojtek242**
This PR fixes all clippy and compiler warnings. I've also added clippy to GitHub actions with the flag `-D warnings` which means the run will fail for any clippy warning.

Closes #114

### CODE REVIEW

File: tests/lib.rs [hunk 1]
```diff
@@ -1,18 +1,25 @@
...
 #[cfg(windows)]
+#[allow(non_camel_case_types)]
 type time_t = libc::c_long;
 
 #[cfg(not(windows))]
+#[allow(non_camel_case_types)]
 type suseconds_t = libc::suseconds_t;
 #[cfg(windows)]
+#[allow(non_camel_case_types)]
 type suseconds_t = libc::c_long;
```
Comment (sekineh) [inline tests/lib.rs:23]: Thanks for the fix. I've regretted the warning produced by these type aliases name.

**Review by sekineh — APPROVED** [review]
